In [3]:
# prelimenary:
from time import time
import numpy as np

np_data = np.arange(1e8)
list_data = list(np_data) # ignore numpy here
# list_data = [1, 2, 3, ...., 1e8]


In [6]:
# list_data --> list with [1, 2, 3, ...., 1e8]

# list
start = time()
list_new_data = []
for i in list_data:
    list_new_data.append(i**2)
list_squared_sum = sum(list_new_data)
print("Time for list: " + str(time()-start))
# print(list_squared_sum)

Time for list: 22.119868278503418


In [7]:
# np_data --> numpy format 

# numpy
start = time()
np_squared_sum = np.sum(np_data**2)
print("Time for numpy: " + str(time()-start))
# print(np_squared_sum)

Time for numpy: 0.45955562591552734


In [12]:

# import 
import numpy as np
my_list = [1, 2, 3, 4, 5]
# array()
my_array = np.array(my_list)
# tolist()
new_list = my_array.tolist() 
print(new_list)

[1, 2, 3, 4, 5]


In [13]:

# mixed list
mixed_list = [3, 2.4, "hi"]
mixed_array = np.array(mixed_list)
print(mixed_array)

['3' '2.4' 'hi']


In [17]:

# Similarities
# print both
print(my_array)
print(my_list)
# index both
print(my_array[0])
print(my_list[0])

# slice both
print(my_array[1:3])
print(my_list[1:3])

# single set value both
my_array[0]=5
my_list[0]=5
print(my_array)
print(my_list)


[1 2 3 4 5]
[1, 2, 3, 4, 5]
1
1
[2 3]
[2, 3]
[5 2 3 4 5]
[5, 2, 3, 4, 5]


In [19]:

# loop through both
for i in my_array:
    print(i)

5
2
3
4
5


In [28]:

# Differences
# addition 
print(my_list+my_list)
print(my_array+my_array)
# multiplication
print(3*my_array)

# more examples:
print(my_array**2)
print(my_array % 2)
print(my_array / 2)
print(np.sin(np.tan(np.cos(my_array))))

[5, 2, 3, 4, 5, 5, 2, 3, 4, 5]
[10  4  6  8 10]
[15  6  9 12 15]
[25  4  9 16 25]
[1 0 1 0 1]
[2.5 1.  1.5 2.  2.5]
[ 0.2874118  -0.42771094 -0.9988889  -0.6932362   0.2874118 ]


In [33]:

# array Generation
print(np.arange(0, 10, 1))
print(np.linspace(1, 6, 8))
print(np.zeros(8))
print(np.full(8, np.pi))

[0 1 2 3 4 5 6 7 8 9]
[1.         1.71428571 2.42857143 3.14285714 3.85714286 4.57142857
 5.28571429 6.        ]
[0. 0. 0. 0. 0. 0. 0. 0.]
[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
 3.14159265 3.14159265]
